package cn.com.infosec.ra.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-09-07T08:29:45.713+08:00
 * Generated source version: 3.4.0
 *
 */
@WebServiceClient(name = "equipmentCertPortService",
                  wsdlLocation = "http://36.110.10.186:50072/NetCertRA6.3.0.1/equipmentCertService.wsdl",
                  targetNamespace = "http://webservice.ra.infosec.com.cn/")
public class EquipmentCertPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.ra.infosec.com.cn/", "equipmentCertPortService");
    public final static QName EquipmentCertPortSoap11 = new QName("http://webservice.ra.infosec.com.cn/", "equipmentCertPortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("http://36.110.10.186:50072/NetCertRA6.3.0.1/equipmentCertService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EquipmentCertPortService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://36.110.10.186:50072/NetCertRA6.3.0.1/equipmentCertService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EquipmentCertPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EquipmentCertPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EquipmentCertPortService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EquipmentCertPortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EquipmentCertPortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EquipmentCertPortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EquipmentCertPort
     */
    @WebEndpoint(name = "equipmentCertPortSoap11")
    public EquipmentCertPort getEquipmentCertPortSoap11() {
        return super.getPort(EquipmentCertPortSoap11, EquipmentCertPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EquipmentCertPort
     */
    @WebEndpoint(name = "equipmentCertPortSoap11")
    public EquipmentCertPort getEquipmentCertPortSoap11(WebServiceFeature... features) {
        return super.getPort(EquipmentCertPortSoap11, EquipmentCertPort.class, features);
    }

}
