package cn.com.infosec.ra.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-09-04T15:52:11.103+08:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://webservice.ra.infosec.com.cn/", name = "equipmentCertPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EquipmentCertPort {

    @WebMethod
    @WebResult(name = "certUpdateResponse", targetNamespace = "http://webservice.ra.infosec.com.cn/", partName = "certUpdateResponse")
    public CertUpdateResponse certUpdate(

        @WebParam(partName = "certUpdateRequest", name = "certUpdateRequest", targetNamespace = "http://webservice.ra.infosec.com.cn/")
        CertUpdateRequest certUpdateRequest
    );

    @WebMethod
    @WebResult(name = "certRevokeResponse", targetNamespace = "http://webservice.ra.infosec.com.cn/", partName = "certRevokeResponse")
    public CertRevokeResponse certRevoke(

        @WebParam(partName = "certRevokeRequest", name = "certRevokeRequest", targetNamespace = "http://webservice.ra.infosec.com.cn/")
        CertRevokeRequest certRevokeRequest
    );

    @WebMethod
    @WebResult(name = "certUnFreezeResponse", targetNamespace = "http://webservice.ra.infosec.com.cn/", partName = "certUnFreezeResponse")
    public CertUnFreezeResponse certUnFreeze(

        @WebParam(partName = "certUnFreezeRequest", name = "certUnFreezeRequest", targetNamespace = "http://webservice.ra.infosec.com.cn/")
        CertUnFreezeRequest certUnFreezeRequest
    );

    @WebMethod
    @WebResult(name = "keyRestoreResponse", targetNamespace = "http://webservice.ra.infosec.com.cn/", partName = "keyRestoreResponse")
    public KeyRestoreResponse keyRestore(

        @WebParam(partName = "keyRestoreRequest", name = "keyRestoreRequest", targetNamespace = "http://webservice.ra.infosec.com.cn/")
        KeyRestoreRequest keyRestoreRequest
    );

    @WebMethod
    @WebResult(name = "certSearchResponse", targetNamespace = "http://webservice.ra.infosec.com.cn/", partName = "certSearchResponse")
    public CertSearchResponse certSearch(

        @WebParam(partName = "certSearchRequest", name = "certSearchRequest", targetNamespace = "http://webservice.ra.infosec.com.cn/")
        CertSearchRequest certSearchRequest
    );

    @WebMethod
    @WebResult(name = "certFreezeResponse", targetNamespace = "http://webservice.ra.infosec.com.cn/", partName = "certFreezeResponse")
    public CertFreezeResponse certFreeze(

        @WebParam(partName = "certFreezeRequest", name = "certFreezeRequest", targetNamespace = "http://webservice.ra.infosec.com.cn/")
        CertFreezeRequest certFreezeRequest
    );

    @WebMethod
    @WebResult(name = "certIssueResponse", targetNamespace = "http://webservice.ra.infosec.com.cn/", partName = "certIssueResponse")
    public CertIssueResponse certIssue(

        @WebParam(partName = "certIssueRequest", name = "certIssueRequest", targetNamespace = "http://webservice.ra.infosec.com.cn/")
        CertIssueRequest certIssueRequest
    );

    @WebMethod
    @WebResult(name = "certTemplateResponse", targetNamespace = "http://webservice.ra.infosec.com.cn/", partName = "certTemplateResponse")
    public CertTemplateResponse certTemplate(

        @WebParam(partName = "certTemplateRequest", name = "certTemplateRequest", targetNamespace = "http://webservice.ra.infosec.com.cn/")
        CertTemplateRequest certTemplateRequest
    );
}
