# Tomcat settings
server:
  port: ${TOMCAT_SERVER_PORT:8080}

# Management settings
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Logging settings
logging:
  level:
    root: WARN
    org:
      springframework:
        security: INFO
        web: ERROR
      hibernate: INFO
    com:
      sample: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: output.log
    max-size: ${LOGGING_FILE_MAX_SIZE:20MB}
    max-history: ${LOGGING_FILE_MAX_HISTORY:100}

# Spring settings
spring:
  profiles:
    active: dev
  application:
    name: cxf-web
